version: "3"

networks:
  dotnet-core-http-net:
    driver: bridge

services:    
  dotnet-core-http-entry-point:
    image: 'yevgenykcx/dotnet-core-http-entry-point'
    networks:
      - dotnet-core-http-net
    ports:
      - '5551:5551'
    environment:
      - NET_CORE_PROPOGATOR_EXAMPLE_URL=http://dotnet-core-http-propagator:5552
      - NET_CORE_SINK_EXAMPLE_URL=http://dotnet-core-http-sink:5553
      - IAST_MANAGER_IP=${IAST_MANAGER_IP}
    # workaround for concurrent IAST agent download bug:
    restart: on-failure
    
  dotnet-core-http-propagator:
    image: 'yevgenykcx/dotnet-core-http-propagator'
    networks:
      - dotnet-core-http-net
    ports:
      - '5552:5552'
    environment:
      - NET_CORE_REST_ENTRY_POINT_EXAMPLE_URL=http://dotnet-core-http-entry-point:5551
      - NET_CORE_SINK_EXAMPLE_URL=http://dotnet-core-http-sink:5553
      - IAST_MANAGER_IP=${IAST_MANAGER_IP}
    # workaround for concurrent IAST agent download bug:
    restart: on-failure
    
  dotnet-core-http-sink:
    image: 'yevgenykcx/dotnet-core-http-sink'
    networks:
      - dotnet-core-http-net
    ports:
      - '5553:5553'
    environment:
      - NET_CORE_REST_ENTRY_POINT_EXAMPLE_URL=http://dotnet-core-http-entry-point:5551
      - NET_CORE_PROPOGATOR_EXAMPLE_URL=http://dotnet-core-http-propagator:5552
      - IAST_MANAGER_IP=${IAST_MANAGER_IP}
    # workaround for concurrent IAST agent download bug:
    restart: on-failure
